# Generated by Django 4.2.1 on 2023-05-28 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('category', models.CharField(choices=[('pl', 'plumbing'), ('el', 'electronics'), ('pw', 'physical work'), ('cl', 'cleaning'), ('tr', 'transportation'), ('ot', 'other')], max_length=2)),
                ('issued', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_app.user')),
            ],
        ),
    ]
