# Generated by Django 4.2.1 on 2023-05-28 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Client',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='user',
            new_name='client',
        ),
    ]
