# Generated by Django 4.2.1 on 2023-06-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0002_rename_user_client_rename_user_offer_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
