# Generated by Django 4.2.1 on 2023-06-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0004_offer_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
    ]
