# Generated by Django 4.2.1 on 2023-06-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0006_remove_offer_client_offer_phone_number_delete_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
