# Generated by Django 4.2.1 on 2023-06-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0007_alter_offer_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
