# Generated by Django 4.2.1 on 2023-06-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0008_rename_phone_number_offer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
