# Generated by Django 4.2.1 on 2023-06-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0011_alter_offer_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='user_id',
            field=models.PositiveBigIntegerField(default=0, max_length=100),
        ),
    ]
