# Generated by Django 4.2.1 on 2023-06-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0012_alter_offer_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='phone',
            field=models.PositiveBigIntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='user_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
