# Generated by Django 4.2.1 on 2023-06-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0013_alter_offer_phone_alter_offer_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.CharField(choices=[('pl', 'plumbing'), ('el', 'electronics'), ('pw', 'physical work'), ('cl', 'cleaning'), ('tr', 'transportation'), ('co', 'construction'), ('ot', 'other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='offer',
            name='phone',
            field=models.PositiveBigIntegerField(),
        ),
    ]
